## Numpy와 닮은 pytorch

In [1]:
from ast import Suite

import torch
print(torch.__version__)

2.7.0


In [5]:
a = torch.tensor([1, 2, 3, 4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape) # .shape -> 지겹게 볼 녀석..

b = torch.tensor([1, 2, 3.1, 4])
print(b)
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로..

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
tensor([1.0000, 2.0000, 3.1000, 4.0000])
torch.float32


In [8]:
A = torch.tensor([ [1, 2], [3, 4]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야함 -> 당연한거쥬?
# A = torch.tensor([ [1, 2], [3, 4, 5]]) # -> error
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.numel()) # 전체 성분의 수

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
2
4


In [15]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.ones((3, 3)))
print(torch.zeros((3,3))) # 3 by 3 of 0
print(torch.arange(3, 10 ,2))
print(torch.arange(0, 1, 0.1))
print(torch.linspace(0, 1, 10))

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0],
        [0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [17]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(a + b)

tensor([5, 7, 9])


In [18]:
# 각 성분끼리의 여러 연산들
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
B = torch.tensor([[4, 5, 6], [7, 8, 9]])

print(A + B)
print(A * B) # 성분끼리의 곱..!
print(A / B)
print(B ** 2)

tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[ 4, 10, 18],
        [28, 40, 54]])
tensor([[0.2500, 0.4000, 0.5000],
        [0.5714, 0.6250, 0.6667]])
tensor([[16, 25, 36],
        [49, 64, 81]])


In [20]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2 by 3
B = torch.tensor([[1, 2], [3, 4], [5, 6]]) # 3 by 2
# print(A * B) # 두 행렬의 shape이 다르니깐 element wise product 안됨.
print(A @ B) # 찐 행렬 곱

tensor([[22, 28],
        [49, 64]])


## Pytorch의 인덱싱 슬라이스

In [25]:
a = torch.arange(1, 10)
print(a)
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:])

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [36]:
# 행렬에 대한 인덱싱과 슬라이싱
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(A[0]) # 하나만 쓰면 행에 대한 인덱싱
print(A[-1])
print(A[1: ])
print(A[:])
print(A[0][2])
print(A[0, 2])

# 다음 두 예제 차이점 확인하기
print(A[: ,2])
print(A[:][2])

print(A[:, [1, 2]])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
tensor([3, 6, 9])
tensor([[2, 3],
        [5, 6],
        [8, 9]])
tensor([7, 8, 9])


In [38]:
# 3차원 행렬 인덱싱
A = torch.tensor([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,
             [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])

print(A)
print(A.shape) # (chanel, row, col)
print(A[0, 1, 2]) # 0 번째 chanel의 1 행의 2열 원소

a=torch.tensor([[[1,2,3,4]]])
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 1, 4])


In [39]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A==3] = 100
print(A) # 그러면 이런 것도 가능하다! (3과 같은 애를 100으로 바꿔줘)

A=torch.tensor([[1,2],
                [3,4],
                [5,6],
                [7,8]])
B=torch.tensor([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=torch.tensor([1,2,3,4])
print(b[ [True,True,False,False] ])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])
tensor([[  1,   2, 100,   4],
        [  5, 100,   7, 100]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [40]:
# tensor로 인덱싱
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A)
A=a[ torch.tensor(2) ] # torch.tensor 안에다가?
print(A)
A=a[ torch.tensor([2,3,4]) ]
print(A)
A=a[ torch.tensor([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

a=torch.tensor([[1,2,3],
                [4,5,6]])
print(a[0])

#! 와우
A=a[ torch.tensor([[0,1],
                   [1,1]]) ]
# [0, 1] -> 0행 1행으로 chanel 하나 구성, [1, 1] -> 1행 1행으로 chanel 하나 더 구성

print(A.shape) # 예를 들어, a[0] = tensor([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [41]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ tensor(bool) ] => A와 같은 shape을 가지는 tensor형 bool이 어디에 True를 가지고 있냐
print(A[ torch.tensor([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,True], [False,True] ])
# 4. A[ tensor ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ torch.tensor([1,1,2,2,2]) ])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor(2)
tensor([2])
tensor([2])
tensor([2, 8])
tensor([[3, 4],
        [3, 4],
        [5, 6],
        [5, 6],
        [5, 6]])


## Pytorch의 여러 함수들


In [14]:
import random
random.seed(12345)
A = torch.randn(3, 3)  # normal -> from N(0,0)
A_ = torch.randn(3, 3) + 10 # from N(10,0)
A__ = torch.randn(3, 3) * 2 + 10 # from N(10, 2)
B = torch.rand(3, 3) # uniform

print(A)
print(A_)
print(A__)
print(B)

print(A[A[:, 0] < 0, :])

tensor([[-0.2544, -1.3183, -0.3435],
        [ 0.6113,  0.1768,  0.3762],
        [ 2.0800,  1.1721, -1.2036]])
tensor([[ 9.9426,  9.1565,  7.8947],
        [10.9868,  9.9789, 10.5273],
        [ 9.8790, 10.7619, 11.0735]])
tensor([[ 9.2190, 11.8505, 10.9910],
        [10.3727,  6.5629,  8.9750],
        [10.2523, 11.3979,  8.6241]])
tensor([[0.5693, 0.3427, 0.6763],
        [0.2189, 0.0231, 0.2305],
        [0.4941, 0.0743, 0.6917]])
tensor([[-0.2544, -1.3183, -0.3435]])


In [16]:
A=torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # torch.exp(torch.tensor(1)) = e^1
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(A)) # 반올림
print(torch.round(A, decimals=2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[-1.4349,  1.2663,  1.0191],
        [-0.8751,  0.6025, -0.8530],
        [-0.8788,  1.9465, -1.2330]])
tensor([[1.4349, 1.2663, 1.0191],
        [0.8751, 0.6025, 0.8530],
        [0.8788, 1.9465, 1.2330]])
tensor([[1.1979, 1.1253, 1.0095],
        [0.9355, 0.7762, 0.9236],
        [0.9374, 1.3952, 1.1104]])
tensor([[0.2381, 3.5476, 2.7706],
        [0.4168, 1.8267, 0.4261],
        [0.4153, 7.0042, 0.2914]])
tensor([[ 0.3611,  0.2361,  0.0189],
        [-0.1334, -0.5066, -0.1590],
        [-0.1292,  0.6660,  0.2094]])
tensor(1.0000)
tensor(1.)
tensor(1.)
tensor([[-1.,  1.,  1.],
        [-1.,  1., -1.],
        [-1.,  2., -1.]])
tensor([[-1.4300,  1.2700,  1.0200],
        [-0.8800,  0.6000, -0.8500],
        [-0.8800,  1.9500, -1.2300]])
tensor([[-2.,  1.,  1.],
        [-1.,  0., -1.],
        [-1.,  1., -2.]])
tensor([[-1.,  2.,  2.],
        [-0.,  1., -0.],
        [-0.,  2., -1.]])


In [23]:
print(torch.sin(torch.tensor(torch.pi/6))) # type(torch.pi) <- float임 만약 tensor와 연산하면 tensor로 바꿔줌
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

print(type(torch.tensor(1)/6))
print(type(torch.tensor(torch.pi / 6)))

tensor(0.5000)
tensor(0.5000)
tensor(1.0000)
tensor(-1.)
<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [24]:
torch.nan # not a number
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [26]:
A=torch.randn(3,4)
print(A)

tensor([[-0.6835,  0.5690,  0.7161, -0.4581],
        [ 0.6097, -0.8827, -1.0898, -0.3668],
        [ 0.7610, -0.6947,  0.7119, -1.9444]])


In [41]:
print(torch.max(A))
print(A.max()) # 이걸 더 자주 쓴다

tensor(0.7610)
tensor(0.7610)


In [28]:
torch.max(A, dim = 0) # dim = 0 -> by each cols

torch.return_types.max(
values=tensor([ 0.7610,  0.5690,  0.7161, -0.3668]),
indices=tensor([2, 0, 0, 1]))

In [29]:
torch.max(A, dim = 1) # dim = 1 -> by each rows

torch.return_types.max(
values=tensor([0.7161, 0.6097, 0.7610]),
indices=tensor([2, 0, 0]))

In [30]:
torch.argmax(A) # output -> index of max value

tensor(8)

In [33]:
a=torch.randn(6,1)
print(a)

tensor([[ 0.4424],
        [ 1.5133],
        [-0.8876],
        [-1.3378],
        [-0.2419],
        [ 0.2492]])


In [38]:
print(torch.sort(a, dim = 0))
print(torch.sort(a, dim = 1))

torch.return_types.sort(
values=tensor([[-1.3378],
        [-0.8876],
        [-0.2419],
        [ 0.2492],
        [ 0.4424],
        [ 1.5133]]),
indices=tensor([[3],
        [2],
        [4],
        [5],
        [0],
        [1]]))
torch.return_types.sort(
values=tensor([[ 0.4424],
        [ 1.5133],
        [-0.8876],
        [-1.3378],
        [-0.2419],
        [ 0.2492]]),
indices=tensor([[0],
        [0],
        [0],
        [0],
        [0],
        [0]]))


In [40]:
print(a.sort(dim = 0))
print(a.sort(dim = 1))

torch.return_types.sort(
values=tensor([[-1.3378],
        [-0.8876],
        [-0.2419],
        [ 0.2492],
        [ 0.4424],
        [ 1.5133]]),
indices=tensor([[3],
        [2],
        [4],
        [5],
        [0],
        [1]]))
torch.return_types.sort(
values=tensor([[ 0.4424],
        [ 1.5133],
        [-0.8876],
        [-1.3378],
        [-0.2419],
        [ 0.2492]]),
indices=tensor([[0],
        [0],
        [0],
        [0],
        [0],
        [0]]))


In [42]:
print(torch.abs(a))
print(a.abs())

tensor([[0.4424],
        [1.5133],
        [0.8876],
        [1.3378],
        [0.2419],
        [0.2492]])
tensor([[0.4424],
        [1.5133],
        [0.8876],
        [1.3378],
        [0.2419],
        [0.2492]])


In [43]:
A = torch.randn(3, 4)
print(A)

tensor([[ 0.0137, -0.9071, -0.0196,  0.3320],
        [-1.1884,  2.1506, -2.5310,  0.6597],
        [-0.3351,  1.0678,  1.7736, -0.7711]])


In [45]:
print(A.sum())
print(torch.sum(A))

tensor(0.2451)
tensor(0.2451)


In [56]:
print(A.sum(dim = 0))
print(torch.sum(A, dim = 0))
print(torch.sum(A, dim = 0, keepdims = True)) # shape 유지

print(A.sum(dim = 0).shape)
print(A.sum(dim = 0, keepdims = True).shape)
print(A.shape)

tensor([-1.5099,  2.3113, -0.7770,  0.2207])
tensor([-1.5099,  2.3113, -0.7770,  0.2207])
tensor([[-1.5099,  2.3113, -0.7770,  0.2207]])
torch.Size([4])
torch.Size([1, 4])
torch.Size([3, 4])


In [48]:
print(A.sum(dim = 1))
print(torch.sum(A, dim = 1))

tensor([-0.5810, -0.9090,  1.7351])
tensor([-0.5810, -0.9090,  1.7351])


In [57]:
# 다 dim, keepdims 셋팅 가능,,
print(A.mean())
print(A.std())

tensor(0.0204)
tensor(1.3073)


In [ ]:
A=torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

In [59]:
A = torch.randint(1 ,5, size = (12, )) # 1부터 5미만 12개 정수 (1 차원은 (N,)과 같이 표현)
print(A)

tensor([3, 1, 4, 2, 3, 4, 4, 4, 4, 2, 3, 2])


In [61]:
print(A.shape)

B = A.reshape(2, 2, 3) # chanel 2, 2 by 3 matrix
print(A)
print(B) # 약간... 흠... 2 2 3이니깐 3부터 시작한다고 생각하고 A에서 3개씩 탁탁탁...
print(B.shape)

torch.Size([12])
tensor([3, 1, 4, 2, 3, 4, 4, 4, 4, 2, 3, 2])
tensor([[[3, 1, 4],
         [2, 3, 4]],

        [[4, 4, 4],
         [2, 3, 2]]])
torch.Size([2, 2, 3])


In [3]:
a=torch.tensor([1,2,3])
b=torch.tensor([2,2,1])
print(torch.sum(a*b)) # 내적
print(torch.dot(a, b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose(1,0)@b)
print(a.permute(1,0)@b) # transpose
print(a.T@b)
print(a.t()@b)

A=torch.randn(4,3,6)
print(A.permute(0,2,1).shape)
print(A.transpose(0,2).shape) # transpose 는 둘끼리 자리 바꾸기만 가능

tensor(9)
tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([4, 6, 3])
torch.Size([6, 3, 4])


In [70]:
print(A)

tensor([[[-0.0112,  1.0773,  0.3169,  2.4944, -0.9286,  1.0073],
         [-0.0108,  0.1317, -0.9642,  1.2723, -0.2647,  1.1200],
         [-0.1801, -0.3052, -0.1002, -0.8464,  0.3043, -1.8037]],

        [[ 0.0526, -0.2447, -1.5836, -1.1202, -0.9550, -0.4123],
         [-0.3169,  0.4753, -0.7320,  1.0433,  0.5793, -0.9376],
         [ 0.1348, -0.8774,  0.1752, -0.5626, -1.4065, -0.8402]],

        [[-0.5600,  0.8141, -0.1095, -0.8370, -1.1488, -1.0946],
         [ 1.1906,  0.2315,  0.0992,  0.0442, -0.5102, -2.9406],
         [-1.6571, -2.3421, -1.2454, -0.9399,  0.2917,  1.8599]],

        [[ 0.3303,  0.0768, -0.8631,  0.5578, -0.2679,  1.1894],
         [ 1.4135,  0.4112,  0.4748,  0.5509,  0.2026,  1.6134],
         [-0.1503,  0.2306,  0.8457,  0.7897,  0.4234,  0.2427]]])


`permute( 0 dim, 1 dim , 2 dim)`
* 0 dim -> 에는 몇 번째 dim을 넣을래?

In [75]:
A.permute(0, 1, 2) == A

tensor([[[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]],

        [[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]],

        [[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]],

        [[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]]])

In [77]:
print(A.shape)
print(A.permute(0, 2, 1).shape)
print(A.permute(0, 2, 1))

torch.Size([4, 3, 6])
torch.Size([4, 6, 3])
tensor([[[-0.0112, -0.0108, -0.1801],
         [ 1.0773,  0.1317, -0.3052],
         [ 0.3169, -0.9642, -0.1002],
         [ 2.4944,  1.2723, -0.8464],
         [-0.9286, -0.2647,  0.3043],
         [ 1.0073,  1.1200, -1.8037]],

        [[ 0.0526, -0.3169,  0.1348],
         [-0.2447,  0.4753, -0.8774],
         [-1.5836, -0.7320,  0.1752],
         [-1.1202,  1.0433, -0.5626],
         [-0.9550,  0.5793, -1.4065],
         [-0.4123, -0.9376, -0.8402]],

        [[-0.5600,  1.1906, -1.6571],
         [ 0.8141,  0.2315, -2.3421],
         [-0.1095,  0.0992, -1.2454],
         [-0.8370,  0.0442, -0.9399],
         [-1.1488, -0.5102,  0.2917],
         [-1.0946, -2.9406,  1.8599]],

        [[ 0.3303,  1.4135, -0.1503],
         [ 0.0768,  0.4112,  0.2306],
         [-0.8631,  0.4748,  0.8457],
         [ 0.5578,  0.5509,  0.7897],
         [-0.2679,  0.2026,  0.4234],
         [ 1.1894,  1.6134,  0.2427]]])


In [79]:
A=torch.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [82]:
# ????
x=torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [11]:
# 나중에 이거 다시 한 번 체크..
A=torch.ones((2,3,4))
B=torch.zeros((2,3,4))

C=torch.vstack([A,B])
D=torch.hstack([A,B]) # v는 0번째 차원, h는 1번째 차원에 쌓는다. -> 잘 안씀.

E=torch.cat([A,B], dim=0) # torch.cat()을 주로 쓴다, dim을 control 하면서
F=torch.cat([A,B], dim=1)
G=torch.cat([A,B], dim=2)

# print(C)
# print(D)
print(E)
#print(F)
#print(G.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [5]:
A = torch.randn(1,1,1,3,1,1,4,1)
print(A)

tensor([[[[[[[[-0.5672],
              [ 0.7019],
              [-0.2483],
              [-0.1935]]]],



           [[[[ 0.4001],
              [ 1.4507],
              [ 0.6544],
              [ 1.4915]]]],



           [[[[ 0.9619],
              [-1.8396],
              [-0.0389],
              [ 1.5653]]]]]]]])


In [6]:
print(A.shape)

torch.Size([1, 1, 1, 3, 1, 1, 4, 1])


In [7]:
print(A.squeeze())

tensor([[-0.5672,  0.7019, -0.2483, -0.1935],
        [ 0.4001,  1.4507,  0.6544,  1.4915],
        [ 0.9619, -1.8396, -0.0389,  1.5653]])


In [9]:
A = torch.randn(3,4)
print(A.shape)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)
print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)

torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


<hr>

chanel이 없는 두 행렬을 쌓고 싶다 -> 2 chanel로..

In [13]:
# unsqueeze는 언제 쓰노,,?
A=torch.ones(3,4)
B=torch.zeros(3,4)
# 이놈들을 합쳐서 2 chanel로 만들고 싶다..

In [14]:
A=A.unsqueeze(dim=0)
B=B.unsqueeze(dim=0)
print(A)
print(B)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [15]:
C=torch.cat([A,B], dim=0)
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


<hr>

In [16]:
A=torch.tensor([[1,2],[3,4]])
B=A.clone() # 주소는 다르게 copy 같은 거임..!
B[0,0]=100

print(B)
print(A)

tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


## @ ?!?

In [17]:
A=torch.randn(5,7)
B=torch.randn(7,10)
C=A@B
print(C.shape)

A=torch.randn(32,5,7)
B=torch.randn(32,7,10)
C=A@B
print(C.shape)

torch.Size([5, 10])
torch.Size([32, 5, 10])


In [18]:
A=torch.randn(32,5,7)
B=torch.randn(7,10)

C=A@B.repeat(32,1,1)
D=A@B

print(C.shape)
print(D.shape)
print((C-D).abs().max())

torch.Size([32, 5, 10])
torch.Size([32, 5, 10])
tensor(0.)


In [21]:
tmp = A@B
tmp.shape

torch.Size([32, 5, 10])

In [22]:
A = torch.rand(2,3)
A_repeat=A.repeat(3,1,3,2)
print(A)
print(A_repeat)
print(A_repeat.shape)

tensor([[0.8521, 0.9931, 0.6623],
        [0.3191, 0.9350, 0.9937]])
tensor([[[[0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937],
          [0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937],
          [0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937]]],


        [[[0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937],
          [0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937],
          [0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937]]],


        [[[0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937],
          [0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.93

## 딥러닝을 가능케한 autograd

In [2]:
x = torch.tensor([1.], requires_grad=True) # requires_grad => 나 이놈 미분할거야~ 라는 뜻
# 정수는 안됨.. Float만됨.
# 미분은 실수공간에서 정의된 개념..

In [3]:
print(x)

tensor([1.], requires_grad=True)


In [4]:
# also..
x = torch.tensor([1. ])
print(x)

x.requires_grad = True
print(x)

tensor([1.])
tensor([1.], requires_grad=True)


In [5]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2
print(y) # 오잉...grad_fn = <PowBackward0>는 뭐농?!

tensor([1.], grad_fn=<PowBackward0>)


$x^2$ - 미분 -> $2x$ --> by `backward()`

In [6]:
print(x.grad)
y.backward()

None


In [7]:
# 미분값
x.grad

tensor([2.])

In [8]:
# 정리하면
x = torch.tensor([1.], requires_grad=True)
y = x ** 2
y.backward()
x.grad # y=x**2을 미분한 2x의 x 값에 1을 대입한 gradient 값

tensor([2.])

In [9]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2
z = 3 * y # 3x^2
print(z) # MulBackward0가 있다..
y.retain_grad() # 중간 체

tensor([3.], grad_fn=<MulBackward0>)


In [10]:
z.backward() # chain rule..
print(x.grad)
print(y.grad)

tensor([6.])
tensor([3.])


$$
{dz\over{dx}} = {dz\over{dy}} {dy\over{dx}}
$$

In [11]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2
z = 3 * y

y.backward() # 이렇게하면 y에서부터 뒤로 넘어감..
# 이건 y를 기준으로 gradient를 계산하겠다는 의미.
# 즉, y를 출력으로 두고, x에 대한 gradient를 구하는 것.
print(x.grad)

tensor([2.])


In [12]:
x=torch.tensor([1.], requires_grad=True)
a=x**2
b=a+1
print(b) # AddBackward0 가 붙어있다!
c=b**2
c.backward()
print(x.grad)

tensor([2.], grad_fn=<AddBackward0>)
tensor([8.])


In [13]:
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= 2*x**2 + y**2
print(z)
z.backward() # z에 대해서 x, y 각각 편미분
print(x.grad)
print(y.grad)

tensor([3.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([2.])


In [14]:
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= y*x**2
z.backward()
print(x.grad)
print(y.grad)

tensor([2.])
tensor([1.])


In [53]:
x=torch.tensor([1., 2., 3.] ,requires_grad=True)
print(x)
y=torch.sum(x**2) # x1**2 + x2**2 + x3**2
print(y)
y.backward() # 편미분 각 각...

print(y)
print(x.grad) # 스칼라를 벡터로 미분

tensor([1., 2., 3.], requires_grad=True)
tensor(14., grad_fn=<SumBackward0>)
tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


In [58]:
# 일부만 훈련 시키고 싶을 떄
x=torch.tensor([1.] ,requires_grad=True)
x.requires_grad=False
# tranfer learning 할 때 필요
y=x**2
print(y)
# y.backward() # error!

tensor([1.])


-> 내가 어떤 만들어 놓은 학습된 모델이 있는데 그 학습된 모델에서 일부분만 학습을 시키고 싶을 때..

나머지 부분을 `requires_grad = False`로 놓고

학습시킬 녀석들만 `requires_grad = True`로 학습

In [19]:
x=torch.tensor([2.] ,requires_grad=True)
x2=x.detach() # detach는 requries_grad = False인 새로운 텐서를 만드는 것
print(x)
print(x2)
y=x**2
y_2 = x2 ** 2
print(y)
y.backward()
x.grad

# y_2.backward() # error,,!

tensor([2.], requires_grad=True)
tensor([2.])
tensor([4.], grad_fn=<PowBackward0>)


tensor([4.])

torch.no_grad, backward() 이거 복습

In [6]:
# detach와 torch.no_grad ==> 중요!!!
x = torch.tensor([1.], requires_grad=True)
# chain rule을 위해 계속 grad_fu을 update 하니까 grad_fn 잠시 안 계산하고 싶을 때 torch.no_grad
# 모델 테스트 시에는 불필요하게 메모리 쓸 필요 없기 때문!
# 여기에서만 미분 ㄴㄴ 하자는 뜻
with torch.no_grad():
    y = x ** 2
    print(x.requires_grad)
    print(y)

print(x.requires_grad)
# y.backward() #error
y = x ** 2
print(y)


True
tensor([1.])
True
tensor([1.], grad_fn=<PowBackward0>)


In [24]:
x = torch.tensor([1.], requires_grad=True)

with torch.no_grad():

    y = x ** 2

    print(x.requires_grad) # 여전히 true

    print(y) # 하지만 여기에서 grad_fn이 사라진걸 알 수 있다.

print(x.requires_grad)

# y.backward() -> error!

y = x ** 2

print(y)

y.backward()
x.grad

# with문 안에서만 grad_fn 업데이트를 하지 않겠다..!

True
tensor([1.], grad_fn=<PowBackward0>)
True
tensor([1.], grad_fn=<PowBackward0>)


tensor([2.])

In [64]:
x=torch.tensor([1.], requires_grad=True)
x=x.detach()
y = x**2
print(x.requires_grad)
print(y)
# y.backward() # error!

False
tensor([1.])


In [5]:
x = torch.tensor([-1.], requires_grad=True)
y = torch.abs(x)
print(y)

tensor([1.], grad_fn=<AbsBackward0>)


In [6]:
y.backward()

In [7]:
x.grad

tensor([-1.])

## 간단한 인공신경망 만들기

In [3]:
import torch
from torch import nn

seed = 1234
torch.manual_seed(seed)

x = torch.tensor([1.])

model = nn.Linear(1, 1) # 입력 node 한 개, 출력 node 한 개인 layer 만듦.

print(model.weight) # 만들면서 initialize 한다.. 책 57페이지 참고
print(model.bias)

# 이제 x를 이 모델에 통과 시켜보자
y = model(x)
print(y)

# 자세히 확인해보자

y = x @ model.weight + model.bias
print(y)

Parameter containing:
tensor([[-0.9420]], requires_grad=True)
Parameter containing:
tensor([-0.1962], requires_grad=True)
tensor([-1.1382], grad_fn=<ViewBackward0>)
tensor([-1.1382], grad_fn=<AddBackward0>)


In [4]:
fc1 = nn.Linear(1, 3) # Fully connected layer

fc2 = nn.Linear(3, 1)

print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)

Parameter containing:
tensor([[-0.4803],
        [-0.2667],
        [-0.8834]], requires_grad=True)
Parameter containing:
tensor([ 0.4013, -0.8964, -0.0637], requires_grad=True)
Parameter containing:
tensor([[ 0.2007, -0.1946,  0.3276]], requires_grad=True)
Parameter containing:
tensor([0.0728], requires_grad=True)


In [12]:
x = torch.tensor([1.])
x = fc1(x)
print(x)

tensor([-0.0790, -1.1631, -0.9471], grad_fn=<ViewBackward0>)


In [13]:
x = fc2(x)
print(x)

tensor([-0.0270], grad_fn=<ViewBackward0>)


In [16]:
# 뜯어보자.. 식은 공식 문서 nn.Linear
x = torch.tensor([1.])
(x @ fc1.weight.T + fc1.bias) @ fc2.weight.T + fc2.bias

tensor([-0.0270], grad_fn=<AddBackward0>)

`nn.Linear`은 개x채x행x열에서 뒤에서 붙어 만들어짐.

예를 들어서 (3, 2, 3, 4)가 있으면

4열을 만들고 0 0 0 0

이놈이 3행이 있는 거고 <p>
0 0 0 0 <p>
0 0 0 0 <p>
0 0 0 0 <p>

그 다음 2개의 채널로 있는거다..!

그리고 이 모음이 총 3개가 있다..!

`nn.Linear` 은 개 채 행 열에서 "채" 형태로 (1D data) 들어오길 기대하는 녀석이다.

(3, 4) -> 4개의 채널을 가진 3개의 데이터 ???

키와 몸무게 5 사람 - > (5, 2)

즉, 노드 하나가 곧 한 채널을 의미한다.

따라서, 데이터 여러개를 통과 시키고 싶다면 개 x 채의 형태로 줘야한다.

**nn.Linear()** 통과 시키려면 개 x 채 의 형태의 데이터를 보내야한다... 이미지 데이터는 채 행 열을 flatten 해서 MLP에 통과 시켜야한다.

In [18]:
fc1 = nn.Linear(1, 3)
fc2 = nn.Linear(3, 1)

x = torch.tensor([1.])

model = nn.Sequential(fc1, fc2) # layer 풀칠 1 - 3 - 1

print(model(x))
print((x @ fc1.weight.T + fc1.bias) @ fc2.weight.T + fc2.bias)

tensor([-0.0901], grad_fn=<ViewBackward0>)
tensor([-0.0901], grad_fn=<AddBackward0>)


In [19]:
model = nn.Sequential(nn.Linear(2,5), # 여기서는 (채, 채) 2개 채널 -> 5개 채널
                      nn.Linear(5, 10),
                      nn.Linear(10, 3))

x = torch.randn(2)

print(x)

print(model(x))

tensor([-1.7873,  0.0538])
tensor([ 0.1002, -0.2118,  0.2712], grad_fn=<ViewBackward0>)


In [21]:
x = torch.randn(1, 2)
print(x)
print(model(x))

tensor([[-0.4876,  0.1944]])
tensor([[0.0431, 0.0027, 0.3130]], grad_fn=<AddmmBackward0>)


In [26]:
x = torch.rand(5, 2) # 개 x 채 => 두 개의 채널 값(키 몸무게)을 가지는 데이터 5개를 통과시킴 -> feature의 수 관점...
print(x)
print(model(x))

tensor([[0.4408, 0.3674],
        [0.7157, 0.8493],
        [0.6216, 0.4546],
        [0.3720, 0.8920],
        [0.3819, 0.8610]])
tensor([[-0.0114,  0.1729,  0.3560],
        [-0.1090,  0.3244,  0.4465],
        [-0.0321,  0.2186,  0.3740],
        [-0.1090,  0.2864,  0.4498],
        [-0.1034,  0.2805,  0.4443]], grad_fn=<AddmmBackward0>)


In [27]:
x = torch.randn(2, 3, 1, 4, 5, 2) # 2만 채! 나머지는 개!

print(model(x).shape)

torch.Size([2, 3, 1, 4, 5, 3])


<hr>

## About class

In [30]:
# 로봇을 만든다고 해보자 -> 로봇의 키가 몇이고 몸무게가 몇이고,,, 안녕이랄고 말하면서 인사를 하는 기능이 있고...
# 클래스는 좀 큰 변수를 만든다고 봐야... a = 1 은 숫자 한 개 들어간 변수..
# a에 숫자 한 개도 넣고 리스트도 넣고 그것들을 가지는 뭔가 기능을 하는 함수를 만들어 넣고 그럴 순 없을까?
# 객체 지향 프로그래밍..

class robot:
    def greeting(self): # method : 클래스 내부의 함수, 첫 번째 매개변수는 무조건 self
        print("Hello")

bot1 = robot() # robot 이라는 클래스에 해당하는 instance 만들기...
bot1.greeting() # 쩜은 "이놈이 가지고 있는" 정도의 의미

Hello


In [34]:
a = [1, 2, 3] # 인스턴스 생성
a.append(4) # a라는 이름의 인스턴스가 append라는 이름의 method 실행

In [32]:
class robot:
    def __init__(self): # initialize 라서 init, 인스턴스 생성 즉시 이 함수로 들어옴!!!!!
        print("__init__으로 들어옴")

bot1 = robot()


__init__으로 들어옴


In [35]:
class robot:
    def __init__(self):
        self.sentence = "안녕"
        # self는 만들어진 인스턴스 자기자신 자체를 가리킴.
        # self.무엇 은 self 내부의 것(변수, 함수)을 가리킴.
        # 클래스 내부의 변수는 속성 이라고 한다.

    def greeting(self):
        #print(sentence) -> error
        print(self.sentence) # 주머니에서 sentence를 꺼내 쓴다..

robot().greeting()

안녕


In [40]:
class robot:
    def __init__(self, height, sentence): # 밖에서 넘어오는 매개변수
        self.height = height # self.height는 밖에서 들어온 height랑은 다른거임.
                             # 클래스 내부에서 써먹을라고 주머니에 넣은 것
        self.sentence = sentence

    def greeting(self):
        #print(sentence) # error
        print(self.sentence)
        print(self.height)

bot1 = robot(180, "안녕")
bot1.greeting()

print(bot1.height)
bot1.height -= 10
print(bot1.height)

안녕
180
180
170


In [43]:
# 밖에서 속성을 못 건드리게 ㄱㄱ
class robot:
    def __init__(self, height, sentence):
        self.__height = height # 비공개로 만들고 싶은 속성은 앞에 밑줄 두 개
        self.sentence = sentence

    def greeting(self):
        print(self.sentence)
        self.__height -= 10 # 내부에선 조작 가능..
        print(self.__height)

bot1 = robot(180, "hi")
bot1.greeting()

# bot1.__height -> 없다고 뜸

hi
170


In [44]:
# 상속 -> 효율화다!
class Robot: # 부모 클래스
    def greeting(self):
        print("안녕하세요")


class Study_dot(Robot): # 자식 클래스, Robot 클래스를 상속 받는다. -> Robot이 가지는 함수 사용 가능!
    def study(self):
        print("열심열심!")


bot = Study_dot()
bot.greeting() # 상속을 받아서 greeting 메서드를 쓸 수 있다..!

안녕하세요


In [47]:
# 메서드 오버라이딩(overrding)

class Robot: # 부모 클래스
    def greeting(self):
        print("안녕하세요")


class Study_dot(Robot): # 자식 클래스
    def greeting(self): # 부모의 greeting을 물려받았으나 여기서 다시 정의하면 덮어써버림..!
        print("공부하는 로봇 열심열심!")

Study_dot().greeting()

공부하는 로봇 열심열심!


In [50]:
# 메서드 오버라이딩(overrding)

class Robot: # 부모 클래스
    def greeting(self):
        print("로봇입니다")


class Study_dot(Robot): # 자식 클래스
    def greeting(self):
        super().greeting() # super()가 부모 클래스를 가리킴 -> 부모의 것을 이렇게 사용하는 것 가능..!
        print("공부하는 로봇입니다!") # 부모의 원래 기능은 유지, 거기에 덧붙이거 싶을 때 오버라이딩 사용 가능

Study_dot().greeting()

로봇입니다
공부하는 로봇입니다!


In [54]:
class robot:
    def func1(self):
        print("부모 클래스의 func1 실행")
        self.money = 100

class Study_bot(robot):
    def func2(self):
        print("자식 클래스의 func2 실행")
        self.book = 10

bot1 = Study_bot()
bot1.func2()
print(bot1.book)
# print(bot1.money) 못 가져옴.. 이게 돈을 받을려면 저 func1이 한 번은 실행이 되어야함! (그럼 __init__ 쓰면 되는거 아닌교?)

bot1.func1() # 부모 함수를 실행해야 부모의 속성더 가져오게 된다.
print(bot1.money)

자식 클래스의 func2 실행
10
부모 클래스의 func1 실행
100


In [56]:
# 딥러닝 코드에선 아래와 같은 코드를 많이 보게 됨
class Robot:
    def __init__(self):
        print("부모 클래스의 init 실행")
        self.money = 100

class StudyBot(Robot):
    def __init__(self):
        super().__init__()
        print("자식 클래스의 init 실향")

StudyBot().money

부모 클래스의 init 실행
자식 클래스의 init 실향


100

In [ ]:
class Robot:
    def __init__(self):
        print("부모 클래스의 init 실행")
        self.money = 100

class StudyBot(Robot):
    def fun2(self): # 자식 클래스에 __init__이 없다면 부모 클래스의 __init__이 자동 호출
        super().__init__()
        print("자식 클래스의 init 실향")

<hr>

In [66]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        # MyModel(nn.Module)에서 super().__init__()는 nn.Module의 초기화 코드를 실헹한다.
        # 이 초기화는 모델 내부의 layer들을 등록하고 추적할 수 있게 해주는 중요한 역할한다.
        # 모델 안에 넣고 학습 가능한 layer로 등록하려면 → 반드시 super().__init__() 호출이 필요하다.
        # 즉, 부모 클래스의 __init__을 상속받고 실행하므로서 .forward, parameter()등을 쓸 수 있다.

        self.fc1 = nn.Linear(2,5)
        self.fc2 = nn.Linear(5,10)
        self.fc3 = nn.Linear(10,3)
        self.sig1 = nn.Sigmoid()
        self.sig2 = nn.Sigmoid()
        self.sig3 = nn.Sigmoid()


    def forward(self, x):
        x = self.fc1(x)
        x = self.sig1(x)
        x = self.fc2(x)
        x = self.sig2(x)
        x = self.fc3(x)
        x = self.sig3(x)
        return x

model = MyModel()
x = torch.randn(5,2)
y = model(x)
print(y)

tensor([[0.4709, 0.5548, 0.5764],
        [0.4677, 0.5541, 0.5756],
        [0.4724, 0.5558, 0.5769],
        [0.4643, 0.5500, 0.5739],
        [0.4662, 0.5526, 0.5750]], grad_fn=<SigmoidBackward0>)


In [68]:
print(model)
print(model.fc1.weight)
print(model.fc2.bias)

MyModel(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
  (sig1): Sigmoid()
  (sig2): Sigmoid()
  (sig3): Sigmoid()
)
Parameter containing:
tensor([[ 0.3675, -0.6347],
        [-0.2294, -0.1896],
        [ 0.0964,  0.6984],
        [-0.1745, -0.1285],
        [-0.0418,  0.6427]], requires_grad=True)
Parameter containing:
tensor([ 0.1930, -0.3964, -0.2680, -0.2347,  0.3082, -0.3488, -0.0661,  0.0317,
        -0.1447,  0.2445], requires_grad=True)


In [70]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.linear = nn.Sequential(nn.Linear(2, 5),
                                    nn.Sigmoid(),
                                    nn.Linear(5, 10),
                                    nn.Sigmoid(),
                                    nn.Linear(10, 3),
                                    nn.Sigmoid())

    def forward(self, x):
        x = self.linear(x)
        return x

model = MyModel()
x = torch.randn(5,2)
y = model(x)
print(y)

tensor([[0.5054, 0.4225, 0.4049],
        [0.4986, 0.4163, 0.4059],
        [0.4987, 0.4145, 0.4024],
        [0.5026, 0.4198, 0.4052],
        [0.5037, 0.4193, 0.4022]], grad_fn=<SigmoidBackward0>)


In [75]:
print(model)
print(model.linear[0].weight)

MyModel(
  (linear): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=5, out_features=10, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=10, out_features=3, bias=True)
    (5): Sigmoid()
  )
)
Parameter containing:
tensor([[-0.5476,  0.5513],
        [ 0.6354, -0.0206],
        [-0.2853,  0.3714],
        [ 0.4735,  0.3682],
        [ 0.0609,  0.0381]], requires_grad=True)


In [76]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.5476,  0.5513],
         [ 0.6354, -0.0206],
         [-0.2853,  0.3714],
         [ 0.4735,  0.3682],
         [ 0.0609,  0.0381]], requires_grad=True),
 Parameter containing:
 tensor([-0.1474,  0.3822,  0.0663, -0.3515, -0.5233], requires_grad=True),
 Parameter containing:
 tensor([[ 0.1071,  0.0535,  0.4161,  0.0495,  0.4465],
         [-0.1768, -0.3146, -0.0586, -0.1630, -0.0744],
         [-0.1373,  0.4090,  0.1985,  0.0725, -0.0073],
         [ 0.4268,  0.1982, -0.1121, -0.4280, -0.4276],
         [-0.1687,  0.0779,  0.0762,  0.2116,  0.2033],
         [-0.1911,  0.2156,  0.2435,  0.1185,  0.3606],
         [-0.3225,  0.0707, -0.0965,  0.4039, -0.3499],
         [ 0.1468, -0.3210, -0.3006, -0.4067,  0.0931],
         [ 0.4076, -0.2256,  0.0321, -0.3652, -0.3216],
         [ 0.1764, -0.0641, -0.0727, -0.2531,  0.2779]], requires_grad=True),
 Parameter containing:
 tensor([-0.3425, -0.2058,  0.2908,  0.1969, -0.4118, -0.4344, -0.2585, -0.4300,
  

In [79]:
# 파라미터 수 구하기
print([p.numel() for p in model.parameters()])
print(sum([p.numel() for p in model.parameters()]))
print(sum([p.numel() for p in model.parameters() if p.requires_grad]))

# numel() -> 텐서 안에 있는 전체 원소의 개수를 반환

[10, 5, 50, 10, 30, 3]
108
108


## Weight initialization

In [80]:
import torch
from torch import nn

Fin=5000
Fout=1000
w = torch.zeros(141, Fin)
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu') # forward pass에서 값의 범위를 유지시켜주기 위함
print(w.std())
print(torch.sqrt(torch.tensor(2/Fin)))
w = torch.zeros(Fout, 212)
nn.init.kaiming_uniform_(w, mode='fan_out', nonlinearity='relu') # backward pass에서 값의 범위를 유지시켜주기 위함
print(w.std())
print(torch.sqrt(torch.tensor(2/Fout)))

# CNN?
N=32
C=64
H=6
W=10
w = torch.zeros(N,C,H,W)
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu')
print(w.std())
print(torch.sqrt(torch.tensor(2/(C*H*W))))

w = torch.zeros(N,C,H,W)
nn.init.kaiming_uniform_(w, mode='fan_out', nonlinearity='relu')
print(w.std())
print(torch.sqrt(torch.tensor(2/(N*H*W))))

tensor(0.0200)
tensor(0.0200)
tensor(0.0448)
tensor(0.0447)
tensor(0.0228)
tensor(0.0228)
tensor(0.0323)
tensor(0.0323)
