In [1]:
import torch
from torch import nn

In [2]:
x = torch.randn(100, 3)
layer = nn.Linear(3, 5)
print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[-0.1108, -0.4514, -0.4163],
        [ 0.3495,  0.0874,  0.4593],
        [ 0.1155,  0.4322, -0.3844],
        [-0.1602,  0.2817, -0.5329],
        [-0.3002,  0.3061, -0.4402]], requires_grad=True)
Parameter containing:
tensor([-0.3681, -0.1281,  0.4130, -0.5634, -0.4491], requires_grad=True)


In [6]:
x = torch.randn(2, 5)
layer = nn.ReLU() # 음수는 0 양수는 linear
print(x)
print(layer(x))

tensor([[ 0.2882,  1.3782,  0.4333,  0.0688,  0.8333],
        [-1.2900,  0.2007, -1.1845, -0.6450, -1.0957]])
tensor([[0.2882, 1.3782, 0.4333, 0.0688, 0.8333],
        [0.0000, 0.2007, 0.0000, 0.0000, 0.0000]])


In [9]:
x = torch.randn(3, 7) # 어떤 노드를 통과된 상태라 하자. 3개, 7 feature
drop = nn.Dropout(p = 0.3) # p는 죽일 확률!! 논문에선 살릴 확률이였다.
print(drop(x)) # 각 개가 통과마다 다르게 drop 된다..!

tensor([[ 0.3459, -1.5823,  2.9730,  1.2473, -0.0000, -1.0688,  1.3578],
        [-0.6621,  0.0000,  2.5391,  3.8966, -0.0255, -0.6990, -0.0000],
        [-0.3712, -0.1636, -0.0000, -1.2739,  0.7860,  1.0813,  0.5819]])


In [10]:
# dropout은 정말 train, test 다르게 작동하나??

class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer = nn.Sequential(nn.Linear(5, 7),
                                        nn.Dropout(p = 0.3))
    def forward(self, x):
        x = self.drop_layer(x)
        return x

model = sample_model()
model.train()
x = torch.randn(3, 5)
print(model(x)) # 0.7의 확률로 죽임

model.eval()
print(model(x)) # 다 살려 그 대신 각 노드마다 0.7 곱

tensor([[-0.2408,  0.0000, -0.0000,  0.0000, -0.0000, -0.0000, -0.0000],
        [-0.0000, -0.8482,  0.1684, -0.4316, -1.1132, -0.0000, -0.0000],
        [-0.0000,  0.0000, -0.0000,  0.4816,  0.0000,  0.7195, -1.1222]],
       grad_fn=<MulBackward0>)
tensor([[-0.1686,  0.9088, -0.3931,  0.2556, -0.6006, -0.2436, -1.5682],
        [-0.1836, -0.5937,  0.1179, -0.3021, -0.7792, -0.3999, -0.3580],
        [-0.0967,  0.9509, -0.3483,  0.3371,  0.0670,  0.5036, -0.7856]],
       grad_fn=<AddmmBackward0>)


In [11]:
layer = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=1) # stride =1, padding =0이 디폴트
layer(torch.randn(32, 1, 5, 5)).shape # 개체행렬!
# nn.linear(3, 5) # 채 채 -> 이놈은 채 또는 개체를 원함 -> 즉, 개 x 3이야지 통과 가능하다.
# nn.Conv2d(3, 5) # 채 채 -> 애는 채 행 열 또는 개 채 행 열을 원함, 개 x 3 x 행 x 열

torch.Size([32, 2, 3, 3])

In [14]:
layer = nn.Conv2d(3, 5, 3, stride =2 , padding =1)
layer(torch.randn(32, 3, 5, 5))
layer.weight.shape

torch.Size([5, 3, 3, 3])