## Numpy와 닮은 pytorch

In [1]:
import torch
print(torch.__version__)

2.7.0


In [5]:
a = torch.tensor([1, 2, 3, 4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape) # .shape -> 지겹게 볼 녀석..

b = torch.tensor([1, 2, 3.1, 4])
print(b)
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로..

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
tensor([1.0000, 2.0000, 3.1000, 4.0000])
torch.float32


In [8]:
A = torch.tensor([ [1, 2], [3, 4]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야함 -> 당연한거쥬?
# A = torch.tensor([ [1, 2], [3, 4, 5]]) # -> error
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.numel()) # 전체 성분의 수

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
2
4


In [15]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.ones((3, 3)))
print(torch.zeros((3,3))) # 3 by 3 of 0
print(torch.arange(3, 10 ,2))
print(torch.arange(0, 1, 0.1))
print(torch.linspace(0, 1, 10))

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0],
        [0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [17]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(a + b)

tensor([5, 7, 9])


In [18]:
# 각 성분끼리의 여러 연산들
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
B = torch.tensor([[4, 5, 6], [7, 8, 9]])

print(A + B)
print(A * B) # 성분끼리의 곱..!
print(A / B)
print(B ** 2)

tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[ 4, 10, 18],
        [28, 40, 54]])
tensor([[0.2500, 0.4000, 0.5000],
        [0.5714, 0.6250, 0.6667]])
tensor([[16, 25, 36],
        [49, 64, 81]])


In [20]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2 by 3
B = torch.tensor([[1, 2], [3, 4], [5, 6]]) # 3 by 2
# print(A * B) # 두 행렬의 shape이 다르니깐 element wise product 안됨.
print(A @ B) # 찐 행렬 곱

tensor([[22, 28],
        [49, 64]])


## Pytorch의 인덱싱 슬라이스

In [25]:
a = torch.arange(1, 10)
print(a)
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:])

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [36]:
# 행렬에 대한 인덱싱과 슬라이싱
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(A[0]) # 하나만 쓰면 행에 대한 인덱싱
print(A[-1])
print(A[1: ])
print(A[:])
print(A[0][2])
print(A[0, 2])

# 다음 두 예제 차이점 확인하기
print(A[: ,2])
print(A[:][2])

print(A[:, [1, 2]])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
tensor([3, 6, 9])
tensor([[2, 3],
        [5, 6],
        [8, 9]])
tensor([7, 8, 9])


In [38]:
# 3차원 행렬 인덱싱
A = torch.tensor([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,
             [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])

print(A)
print(A.shape) # (chanel, row, col)
print(A[0, 1, 2]) # 0 번째 chanel의 1 행의 2열 원소

a=torch.tensor([[[1,2,3,4]]])
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 1, 4])


In [39]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A==3] = 100
print(A) # 그러면 이런 것도 가능하다! (3과 같은 애를 100으로 바꿔줘)

A=torch.tensor([[1,2],
                [3,4],
                [5,6],
                [7,8]])
B=torch.tensor([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=torch.tensor([1,2,3,4])
print(b[ [True,True,False,False] ])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])
tensor([[  1,   2, 100,   4],
        [  5, 100,   7, 100]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [40]:
# tensor로 인덱싱
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A)
A=a[ torch.tensor(2) ] # torch.tensor 안에다가?
print(A)
A=a[ torch.tensor([2,3,4]) ]
print(A)
A=a[ torch.tensor([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

a=torch.tensor([[1,2,3],
                [4,5,6]])
print(a[0])

#! 와우
A=a[ torch.tensor([[0,1],
                   [1,1]]) ]
# [0, 1] -> 0행 1행으로 chanel 하나 구성, [1, 1] -> 1행 1행으로 chanel 하나 더 구성

print(A.shape) # 예를 들어, a[0] = tensor([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [41]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ tensor(bool) ] => A와 같은 shape을 가지는 tensor형 bool이 어디에 True를 가지고 있냐
print(A[ torch.tensor([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,True], [False,True] ])
# 4. A[ tensor ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ torch.tensor([1,1,2,2,2]) ])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor(2)
tensor([2])
tensor([2])
tensor([2, 8])
tensor([[3, 4],
        [3, 4],
        [5, 6],
        [5, 6],
        [5, 6]])


## Pytorch의 여러 함수들


In [14]:
import random
random.seed(12345)
A = torch.randn(3, 3)  # normal -> from N(0,0)
A_ = torch.randn(3, 3) + 10 # from N(10,0)
A__ = torch.randn(3, 3) * 2 + 10 # from N(10, 2)
B = torch.rand(3, 3) # uniform

print(A)
print(A_)
print(A__)
print(B)

print(A[A[:, 0] < 0, :])

tensor([[-0.2544, -1.3183, -0.3435],
        [ 0.6113,  0.1768,  0.3762],
        [ 2.0800,  1.1721, -1.2036]])
tensor([[ 9.9426,  9.1565,  7.8947],
        [10.9868,  9.9789, 10.5273],
        [ 9.8790, 10.7619, 11.0735]])
tensor([[ 9.2190, 11.8505, 10.9910],
        [10.3727,  6.5629,  8.9750],
        [10.2523, 11.3979,  8.6241]])
tensor([[0.5693, 0.3427, 0.6763],
        [0.2189, 0.0231, 0.2305],
        [0.4941, 0.0743, 0.6917]])
tensor([[-0.2544, -1.3183, -0.3435]])


In [16]:
A=torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # torch.exp(torch.tensor(1)) = e^1
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(A)) # 반올림
print(torch.round(A, decimals=2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[-1.4349,  1.2663,  1.0191],
        [-0.8751,  0.6025, -0.8530],
        [-0.8788,  1.9465, -1.2330]])
tensor([[1.4349, 1.2663, 1.0191],
        [0.8751, 0.6025, 0.8530],
        [0.8788, 1.9465, 1.2330]])
tensor([[1.1979, 1.1253, 1.0095],
        [0.9355, 0.7762, 0.9236],
        [0.9374, 1.3952, 1.1104]])
tensor([[0.2381, 3.5476, 2.7706],
        [0.4168, 1.8267, 0.4261],
        [0.4153, 7.0042, 0.2914]])
tensor([[ 0.3611,  0.2361,  0.0189],
        [-0.1334, -0.5066, -0.1590],
        [-0.1292,  0.6660,  0.2094]])
tensor(1.0000)
tensor(1.)
tensor(1.)
tensor([[-1.,  1.,  1.],
        [-1.,  1., -1.],
        [-1.,  2., -1.]])
tensor([[-1.4300,  1.2700,  1.0200],
        [-0.8800,  0.6000, -0.8500],
        [-0.8800,  1.9500, -1.2300]])
tensor([[-2.,  1.,  1.],
        [-1.,  0., -1.],
        [-1.,  1., -2.]])
tensor([[-1.,  2.,  2.],
        [-0.,  1., -0.],
        [-0.,  2., -1.]])


In [23]:
print(torch.sin(torch.tensor(torch.pi/6))) # type(torch.pi) <- float임 만약 tensor와 연산하면 tensor로 바꿔줌
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

print(type(torch.tensor(1)/6))
print(type(torch.tensor(torch.pi / 6)))

tensor(0.5000)
tensor(0.5000)
tensor(1.0000)
tensor(-1.)
<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [24]:
torch.nan # not a number
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [26]:
A=torch.randn(3,4)
print(A)

tensor([[-0.6835,  0.5690,  0.7161, -0.4581],
        [ 0.6097, -0.8827, -1.0898, -0.3668],
        [ 0.7610, -0.6947,  0.7119, -1.9444]])


In [41]:
print(torch.max(A))
print(A.max()) # 이걸 더 자주 쓴다

tensor(0.7610)
tensor(0.7610)


In [28]:
torch.max(A, dim = 0) # dim = 0 -> by each cols

torch.return_types.max(
values=tensor([ 0.7610,  0.5690,  0.7161, -0.3668]),
indices=tensor([2, 0, 0, 1]))

In [29]:
torch.max(A, dim = 1) # dim = 1 -> by each rows

torch.return_types.max(
values=tensor([0.7161, 0.6097, 0.7610]),
indices=tensor([2, 0, 0]))

In [30]:
torch.argmax(A) # output -> index of max value

tensor(8)

In [33]:
a=torch.randn(6,1)
print(a)

tensor([[ 0.4424],
        [ 1.5133],
        [-0.8876],
        [-1.3378],
        [-0.2419],
        [ 0.2492]])


In [38]:
print(torch.sort(a, dim = 0))
print(torch.sort(a, dim = 1))

torch.return_types.sort(
values=tensor([[-1.3378],
        [-0.8876],
        [-0.2419],
        [ 0.2492],
        [ 0.4424],
        [ 1.5133]]),
indices=tensor([[3],
        [2],
        [4],
        [5],
        [0],
        [1]]))
torch.return_types.sort(
values=tensor([[ 0.4424],
        [ 1.5133],
        [-0.8876],
        [-1.3378],
        [-0.2419],
        [ 0.2492]]),
indices=tensor([[0],
        [0],
        [0],
        [0],
        [0],
        [0]]))


In [40]:
print(a.sort(dim = 0))
print(a.sort(dim = 1))

torch.return_types.sort(
values=tensor([[-1.3378],
        [-0.8876],
        [-0.2419],
        [ 0.2492],
        [ 0.4424],
        [ 1.5133]]),
indices=tensor([[3],
        [2],
        [4],
        [5],
        [0],
        [1]]))
torch.return_types.sort(
values=tensor([[ 0.4424],
        [ 1.5133],
        [-0.8876],
        [-1.3378],
        [-0.2419],
        [ 0.2492]]),
indices=tensor([[0],
        [0],
        [0],
        [0],
        [0],
        [0]]))


In [42]:
print(torch.abs(a))
print(a.abs())

tensor([[0.4424],
        [1.5133],
        [0.8876],
        [1.3378],
        [0.2419],
        [0.2492]])
tensor([[0.4424],
        [1.5133],
        [0.8876],
        [1.3378],
        [0.2419],
        [0.2492]])


In [43]:
A = torch.randn(3, 4)
print(A)

tensor([[ 0.0137, -0.9071, -0.0196,  0.3320],
        [-1.1884,  2.1506, -2.5310,  0.6597],
        [-0.3351,  1.0678,  1.7736, -0.7711]])


In [45]:
print(A.sum())
print(torch.sum(A))

tensor(0.2451)
tensor(0.2451)


In [56]:
print(A.sum(dim = 0))
print(torch.sum(A, dim = 0))
print(torch.sum(A, dim = 0, keepdims = True)) # shape 유지

print(A.sum(dim = 0).shape)
print(A.sum(dim = 0, keepdims = True).shape)
print(A.shape)

tensor([-1.5099,  2.3113, -0.7770,  0.2207])
tensor([-1.5099,  2.3113, -0.7770,  0.2207])
tensor([[-1.5099,  2.3113, -0.7770,  0.2207]])
torch.Size([4])
torch.Size([1, 4])
torch.Size([3, 4])


In [48]:
print(A.sum(dim = 1))
print(torch.sum(A, dim = 1))

tensor([-0.5810, -0.9090,  1.7351])
tensor([-0.5810, -0.9090,  1.7351])


In [57]:
# 다 dim, keepdims 셋팅 가능,,
print(A.mean())
print(A.std())

tensor(0.0204)
tensor(1.3073)


In [ ]:
A=torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

In [59]:
A = torch.randint(1 ,5, size = (12, )) # 1부터 5미만 12개 정수 (1 차원은 (N,)과 같이 표현)
print(A)

tensor([3, 1, 4, 2, 3, 4, 4, 4, 4, 2, 3, 2])


In [61]:
print(A.shape)

B = A.reshape(2, 2, 3) # chanel 2, 2 by 3 matrix
print(A)
print(B) # 약간... 흠... 2 2 3이니깐 3부터 시작한다고 생각하고 A에서 3개씩 탁탁탁...
print(B.shape)

torch.Size([12])
tensor([3, 1, 4, 2, 3, 4, 4, 4, 4, 2, 3, 2])
tensor([[[3, 1, 4],
         [2, 3, 4]],

        [[4, 4, 4],
         [2, 3, 2]]])
torch.Size([2, 2, 3])


In [3]:
a=torch.tensor([1,2,3])
b=torch.tensor([2,2,1])
print(torch.sum(a*b)) # 내적
print(torch.dot(a, b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose(1,0)@b)
print(a.permute(1,0)@b) # transpose
print(a.T@b)
print(a.t()@b)

A=torch.randn(4,3,6)
print(A.permute(0,2,1).shape)
print(A.transpose(0,2).shape) # transpose 는 둘끼리 자리 바꾸기만 가능

tensor(9)
tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([4, 6, 3])
torch.Size([6, 3, 4])


In [70]:
print(A)

tensor([[[-0.0112,  1.0773,  0.3169,  2.4944, -0.9286,  1.0073],
         [-0.0108,  0.1317, -0.9642,  1.2723, -0.2647,  1.1200],
         [-0.1801, -0.3052, -0.1002, -0.8464,  0.3043, -1.8037]],

        [[ 0.0526, -0.2447, -1.5836, -1.1202, -0.9550, -0.4123],
         [-0.3169,  0.4753, -0.7320,  1.0433,  0.5793, -0.9376],
         [ 0.1348, -0.8774,  0.1752, -0.5626, -1.4065, -0.8402]],

        [[-0.5600,  0.8141, -0.1095, -0.8370, -1.1488, -1.0946],
         [ 1.1906,  0.2315,  0.0992,  0.0442, -0.5102, -2.9406],
         [-1.6571, -2.3421, -1.2454, -0.9399,  0.2917,  1.8599]],

        [[ 0.3303,  0.0768, -0.8631,  0.5578, -0.2679,  1.1894],
         [ 1.4135,  0.4112,  0.4748,  0.5509,  0.2026,  1.6134],
         [-0.1503,  0.2306,  0.8457,  0.7897,  0.4234,  0.2427]]])


`permute( 0 dim, 1 dim , 2 dim)`
* 0 dim -> 에는 몇 번째 dim을 넣을래?

In [75]:
A.permute(0, 1, 2) == A

tensor([[[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]],

        [[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]],

        [[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]],

        [[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]]])

In [77]:
print(A.shape)
print(A.permute(0, 2, 1).shape)
print(A.permute(0, 2, 1))

torch.Size([4, 3, 6])
torch.Size([4, 6, 3])
tensor([[[-0.0112, -0.0108, -0.1801],
         [ 1.0773,  0.1317, -0.3052],
         [ 0.3169, -0.9642, -0.1002],
         [ 2.4944,  1.2723, -0.8464],
         [-0.9286, -0.2647,  0.3043],
         [ 1.0073,  1.1200, -1.8037]],

        [[ 0.0526, -0.3169,  0.1348],
         [-0.2447,  0.4753, -0.8774],
         [-1.5836, -0.7320,  0.1752],
         [-1.1202,  1.0433, -0.5626],
         [-0.9550,  0.5793, -1.4065],
         [-0.4123, -0.9376, -0.8402]],

        [[-0.5600,  1.1906, -1.6571],
         [ 0.8141,  0.2315, -2.3421],
         [-0.1095,  0.0992, -1.2454],
         [-0.8370,  0.0442, -0.9399],
         [-1.1488, -0.5102,  0.2917],
         [-1.0946, -2.9406,  1.8599]],

        [[ 0.3303,  1.4135, -0.1503],
         [ 0.0768,  0.4112,  0.2306],
         [-0.8631,  0.4748,  0.8457],
         [ 0.5578,  0.5509,  0.7897],
         [-0.2679,  0.2026,  0.4234],
         [ 1.1894,  1.6134,  0.2427]]])


In [79]:
A=torch.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [82]:
# ????
x=torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [11]:
# 나중에 이거 다시 한 번 체크..
A=torch.ones((2,3,4))
B=torch.zeros((2,3,4))

C=torch.vstack([A,B])
D=torch.hstack([A,B]) # v는 0번째 차원, h는 1번째 차원에 쌓는다. -> 잘 안씀.

E=torch.cat([A,B], dim=0) # torch.cat()을 주로 쓴다, dim을 control 하면서
F=torch.cat([A,B], dim=1)
G=torch.cat([A,B], dim=2)

# print(C)
# print(D)
print(E)
#print(F)
#print(G.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [5]:
A = torch.randn(1,1,1,3,1,1,4,1)
print(A)

tensor([[[[[[[[-0.5672],
              [ 0.7019],
              [-0.2483],
              [-0.1935]]]],



           [[[[ 0.4001],
              [ 1.4507],
              [ 0.6544],
              [ 1.4915]]]],



           [[[[ 0.9619],
              [-1.8396],
              [-0.0389],
              [ 1.5653]]]]]]]])


In [6]:
print(A.shape)

torch.Size([1, 1, 1, 3, 1, 1, 4, 1])


In [7]:
print(A.squeeze())

tensor([[-0.5672,  0.7019, -0.2483, -0.1935],
        [ 0.4001,  1.4507,  0.6544,  1.4915],
        [ 0.9619, -1.8396, -0.0389,  1.5653]])


In [9]:
A = torch.randn(3,4)
print(A.shape)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)
print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)

torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


<hr>

chanel이 없는 두 행렬을 쌓고 싶다 -> 2 chanel로..

In [13]:
# unsqueeze는 언제 쓰노,,?
A=torch.ones(3,4)
B=torch.zeros(3,4)
# 이놈들을 합쳐서 2 chanel로 만들고 싶다..

In [14]:
A=A.unsqueeze(dim=0)
B=B.unsqueeze(dim=0)
print(A)
print(B)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [15]:
C=torch.cat([A,B], dim=0)
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


<hr>

In [16]:
A=torch.tensor([[1,2],[3,4]])
B=A.clone() # 주소는 다르게 copy 같은 거임..!
B[0,0]=100

print(B)
print(A)

tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


## @ ?!?

In [17]:
A=torch.randn(5,7)
B=torch.randn(7,10)
C=A@B
print(C.shape)

A=torch.randn(32,5,7)
B=torch.randn(32,7,10)
C=A@B
print(C.shape)

torch.Size([5, 10])
torch.Size([32, 5, 10])


In [18]:
A=torch.randn(32,5,7)
B=torch.randn(7,10)

C=A@B.repeat(32,1,1)
D=A@B

print(C.shape)
print(D.shape)
print((C-D).abs().max())

torch.Size([32, 5, 10])
torch.Size([32, 5, 10])
tensor(0.)


In [21]:
tmp = A@B
tmp.shape

torch.Size([32, 5, 10])

In [22]:
A = torch.rand(2,3)
A_repeat=A.repeat(3,1,3,2)
print(A)
print(A_repeat)
print(A_repeat.shape)

tensor([[0.8521, 0.9931, 0.6623],
        [0.3191, 0.9350, 0.9937]])
tensor([[[[0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937],
          [0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937],
          [0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937]]],


        [[[0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937],
          [0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937],
          [0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937]]],


        [[[0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.9350, 0.9937, 0.3191, 0.9350, 0.9937],
          [0.8521, 0.9931, 0.6623, 0.8521, 0.9931, 0.6623],
          [0.3191, 0.93

## 딥러닝을 가능케한 autograd

In [24]:
x = torch.tensor([1.], requires_grad=True) # requires_grad => 나 이놈 미분할거야~ 라는 뜻
# 정수는 안됨.. Float만됨.
# 미분은 실수공간에서 정의된 개념..

In [25]:
print(x)

tensor([1.], requires_grad=True)


In [26]:
# also..
x = torch.tensor([1. ])
print(x)
x.requires_grad = True
print(x)

tensor([1.])
tensor([1.], requires_grad=True)


In [33]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2
print(y) # 오잉...grad_fn = <PowBackward0>는 뭐농?!

tensor([1.], grad_fn=<PowBackward0>)


$x^2$ - 미분 -> $2x$ --> by `backward()`

In [34]:
print(x.grad)
y.backward()

None


In [31]:
# 미분값
x.grad

tensor([2.])

In [35]:
# 정리하면
x = torch.tensor([1.], requires_grad=True)
y = x ** 2
y.backward()
x.grad # y=x**2을 미분한 2x의 x 값에 1을 대입한 gradient 값

tensor([2.])

In [4]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2
z = 3 * y # 3x^2
print(z) # MulBackward0가 있다..
y.retain_grad() # 중간 체

tensor([3.], grad_fn=<MulBackward0>)


In [5]:
z.backward() # chain rule..
print(x.grad)
print(y.grad)

tensor([6.])
tensor([3.])


$$
{dz\over{dx}} = {dz\over{dy}} {dy\over{dx}}
$$

In [49]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2
z = 3 * y

y.backward() # 이렇게하면 y에서부터 뒤로 넘어감..
# 이건 y를 기준으로 gradient를 계산하겠다는 의미.
# 즉, y를 출력으로 두고, x에 대한 gradient를 구하는 것.
print(x.grad)

tensor([2.])


In [50]:
x=torch.tensor([1.], requires_grad=True)
a=x**2
b=a+1
print(b) # AddBackward0 가 붙어있다!
c=b**2
c.backward()
print(x.grad)

tensor([2.], grad_fn=<AddBackward0>)
tensor([8.])


In [51]:
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= 2*x**2 + y**2
print(z)
z.backward() # z에 대해서 x, y 각각 편미분
print(x.grad)
print(y.grad)

tensor([3.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([2.])


In [52]:
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= y*x**2
z.backward()
print(x.grad)
print(y.grad)

tensor([2.])
tensor([1.])


In [53]:
x=torch.tensor([1., 2., 3.] ,requires_grad=True)
print(x)
y=torch.sum(x**2) # x1**2 + x2**2 + x3**2
print(y)
y.backward() # 편미분 각 각...

print(y)
print(x.grad) # 스칼라를 벡터로 미분

tensor([1., 2., 3.], requires_grad=True)
tensor(14., grad_fn=<SumBackward0>)
tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


In [58]:
# 일부만 훈련 시키고 싶을 떄
x=torch.tensor([1.] ,requires_grad=True)
x.requires_grad=False
# tranfer learning 할 때 필요
y=x**2
print(y)
# y.backward() # error!

tensor([1.])


In [59]:
x=torch.tensor([2.] ,requires_grad=True)
x=x.detach() # detach도 많이 쓰이는 듯
print(x)
y=x**2
print(y)

tensor([2.])
tensor([4.])


torch.no_grad, backward() 이거 복습

In [6]:
# detach와 torch.no_grad ==> 중요!!!
x = torch.tensor([1.], requires_grad=True)
# chain rule을 위해 계속 grad_fu을 update 하니까 grad_fn 잠시 안 계산하고 싶을 때 torch.no_grad
# 모델 테스트 시에는 불필요하게 메모리 쓸 필요 없기 때문!
# 여기에서만 미분 ㄴㄴ 하자는 뜻
with torch.no_grad():
    y = x ** 2
    print(x.requires_grad)
    print(y)

print(x.requires_grad)
# y.backward() #error
y = x ** 2
print(y)


True
tensor([1.])
True
tensor([1.], grad_fn=<PowBackward0>)


In [14]:
# 정리하면
x = torch.tensor([1.], requires_grad=True)

with torch.no_grad():
    y = x ** 2
    print(y)
    #y.backward()
    #x.gred

y = x ** 2
print(y)
y.backward()
print(x.grad)

tensor([1.])
tensor([1.], grad_fn=<PowBackward0>)
tensor([2.])


In [64]:
x=torch.tensor([1.], requires_grad=True)
x=x.detach()
y = x**2
print(x.requires_grad)
print(y)
# y.backward() # error!

False
tensor([1.])


In [5]:
x = torch.tensor([-1.], requires_grad=True)
y = torch.abs(x)
print(y)

tensor([1.], grad_fn=<AbsBackward0>)


In [6]:
y.backward()

In [7]:
x.grad

tensor([-1.])