## Numpy와 닮은 pytorch

In [3]:
import torch
print(torch.__version__)

2.7.0


In [5]:
a = torch.tensor([1, 2, 3, 4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape) # .shape -> 지겹게 볼 녀석..

b = torch.tensor([1, 2, 3.1, 4])
print(b)
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로..

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
tensor([1.0000, 2.0000, 3.1000, 4.0000])
torch.float32


In [8]:
A = torch.tensor([ [1, 2], [3, 4]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야함 -> 당연한거쥬?
# A = torch.tensor([ [1, 2], [3, 4, 5]]) # -> error
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.numel()) # 전체 성분의 수

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
2
4


In [15]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.ones((3, 3)))
print(torch.zeros((3,3))) # 3 by 3 of 0
print(torch.arange(3, 10 ,2))
print(torch.arange(0, 1, 0.1))
print(torch.linspace(0, 1, 10))

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0],
        [0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [17]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(a + b)

tensor([5, 7, 9])


In [18]:
# 각 성분끼리의 여러 연산들
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
B = torch.tensor([[4, 5, 6], [7, 8, 9]])

print(A + B)
print(A * B) # 성분끼리의 곱..!
print(A / B)
print(B ** 2)

tensor([[ 5,  7,  9],
        [11, 13, 15]])
tensor([[ 4, 10, 18],
        [28, 40, 54]])
tensor([[0.2500, 0.4000, 0.5000],
        [0.5714, 0.6250, 0.6667]])
tensor([[16, 25, 36],
        [49, 64, 81]])


In [20]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2 by 3
B = torch.tensor([[1, 2], [3, 4], [5, 6]]) # 3 by 2
# print(A * B) # 두 행렬의 shape이 다르니깐 element wise product 안됨.
print(A @ B) # 찐 행렬 곱

tensor([[22, 28],
        [49, 64]])


## Pytorch의 인덱싱 슬라이스

In [25]:
a = torch.arange(1, 10)
print(a)
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:])

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [36]:
# 행렬에 대한 인덱싱과 슬라이싱
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(A[0]) # 하나만 쓰면 행에 대한 인덱싱
print(A[-1])
print(A[1: ])
print(A[:])
print(A[0][2])
print(A[0, 2])

# 다음 두 예제 차이점 확인하기
print(A[: ,2])
print(A[:][2])

print(A[:, [1, 2]])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
tensor([3, 6, 9])
tensor([[2, 3],
        [5, 6],
        [8, 9]])
tensor([7, 8, 9])


In [38]:
# 3차원 행렬 인덱싱
A = torch.tensor([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,
             [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])

print(A)
print(A.shape) # (chanel, row, col)
print(A[0, 1, 2]) # 0 번째 chanel의 1 행의 2열 원소

a=torch.tensor([[[1,2,3,4]]])
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 1, 4])


In [39]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A==3] = 100
print(A) # 그러면 이런 것도 가능하다! (3과 같은 애를 100으로 바꿔줘)

A=torch.tensor([[1,2],
                [3,4],
                [5,6],
                [7,8]])
B=torch.tensor([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=torch.tensor([1,2,3,4])
print(b[ [True,True,False,False] ])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])
tensor([[  1,   2, 100,   4],
        [  5, 100,   7, 100]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [40]:
# tensor로 인덱싱
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A)
A=a[ torch.tensor(2) ] # torch.tensor 안에다가?
print(A)
A=a[ torch.tensor([2,3,4]) ]
print(A)
A=a[ torch.tensor([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

a=torch.tensor([[1,2,3],
                [4,5,6]])
print(a[0])

#! 와우
A=a[ torch.tensor([[0,1],
                   [1,1]]) ]
# [0, 1] -> 0행 1행으로 chanel 하나 구성, [1, 1] -> 1행 1행으로 chanel 하나 더 구성

print(A.shape) # 예를 들어, a[0] = tensor([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [41]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ tensor(bool) ] => A와 같은 shape을 가지는 tensor형 bool이 어디에 True를 가지고 있냐
print(A[ torch.tensor([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,True], [False,True] ])
# 4. A[ tensor ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ torch.tensor([1,1,2,2,2]) ])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor(2)
tensor([2])
tensor([2])
tensor([2, 8])
tensor([[3, 4],
        [3, 4],
        [5, 6],
        [5, 6],
        [5, 6]])


## Pytorch의 여러 함수들


In [ ]:
# 1:04